spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082

zup:
  file:
    upload:
      path: "upload/"
  email:
    user: "email@hotmail.com"
    password: "SenhaDoEmail"
    transport:
      protocol: "smtp"
    smtp:
      host: "smtp.live.com"
      port: "587"
      auth: "true"
      starttls:
        enable: "true"
      socketFactory:
        fallback: "false"
        port: "587"

application:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  swagger:
    enabled: true